export const MockedOrders = [
  {
    id: "#13702574",
    status: "Preparing",
    date: "04/10/2021",
    hour: "02:39",
    place: "Colorado Springs",
    clientName: "Matthew Collins",
    clientEmail: "c.matthews@outlook.com",
    deliveryCompany: "DHL",
    trackingCode: "705-610844",
    product: "Hourglass Wallet on Chain, Void Butterfly Sunglasses",
    price: "$2,198.03",
    paymentMethodType: "Credit Card",
    paymentMethod: "**** 9171",
  },
  {
    id: "#75842541",
    status: "Sent",
    date: "04/05/2021",
    hour: "05:50",
    place: "Mesa",
    clientName: "Alfred Ellis",
    clientEmail: "j.hawkins@verizon.net",
    deliveryCompany: "UPS",
    trackingCode: "710-981371",
    product:
      "Pleated Tracksuit, Ville Supple Large Purse, Hooded Bathrobe, +6 more",
    price: "$8,555.47",
    paymentMethodType: "Credit Card",
    paymentMethod: "**** 6282",
  },
  {
    id: "#77233897",
    status: "Returned",
    date: "04/04/2021",
    hour: "09:05",
    place: "Raleigh",
    clientName: "Jon Grant",
    clientEmail: "g.powers@msn.com",
    deliveryCompany: "DHL Express",
    trackingCode: "886-552845",
    product: "One Size Tracksuit, Dummy Earings, Swift Oval Sunglasses",
    price: "$3,485.69",
    paymentMethodType: "Debit Card",
    paymentMethod: "**** 2756",
  },
  {
    id: "#38863033",
    status: "Preparing",
    date: "04/03/2021",
    hour: "03:13",
    place: "Las Vegas",
    clientName: "Ben Scott",
    clientEmail: "r.grant@gmail.com",
    deliveryCompany: "DHL",
    trackingCode: "416-253244",
    product: "New Fur Coat",
    price: "$1,039.32",
    paymentMethodType: "Credit Card",
    paymentMethod: "**** 6337",
  },
  {
    id: "#32179451",
    status: "Sent",
    date: "04/03/2021",
    hour: "11:08",
    place: "Los Angeles",
    clientName: "Tara Walsh",
    clientEmail: "v.kelley@msn.com",
    deliveryCompany: "FedEx",
    trackingCode: "603-577113",
    product: "Hybrid Shirt Pants, Rhino Derby, Punk Tag Necklace",
    price: "$3,607.34",
    paymentMethodType: "PayPal",
    paymentMethod: "",
  },
  {
    id: "#62927505",
    status: "Sent",
    date: "04/02/2021",
    hour: "21:18",
    place: "Virginia Beach",
    clientName: "Ruby Little",
    clientEmail: "jordan.davidson@aol.com",
    deliveryCompany: "UPS",
    trackingCode: "716-354651",
    product: "Mask Turtleneck, Baggy Sweatpants, Sporty Hood, +3 more",
    price: "$6,883.83",
    paymentMethodType: "Bank Transfer",
    paymentMethod: "",
  },
  {
    id: "#53453875",
    status: "Cancelled",
    date: "03/29/2021",
    hour: "22:54",
    place: "Louisville",
    clientName: "Jordan Mason",
    clientEmail: "larry.cunningham@outlook.com",
    deliveryCompany: "DHL",
    trackingCode: "298-698777",
    product: "Hooded Carcoat",
    price: "$2,449.00",
    paymentMethodType: "Credit Card",
    paymentMethod: "**** 3539",
  },
  {
    id: "#40271151",
    status: "Returned",
    date: "03/21/2021",
    hour: "14:39",
    place: "Washington",
    clientName: "Lydia Williamson",
    clientEmail: "georgia.hunt@live.com",
    deliveryCompany: "FedEx",
    trackingCode: "623-380017",
    product: "Pajama Shirt, Oversize Shorts, Tracksuit Cap, Chainmail Top",
    price: "$3,888.53",
    paymentMethodType: "Debit Card",
    paymentMethod: "**** 6449",
  },
  {
    id: "#76446673",
    status: "Delivered",
    date: "03/18/2021",
    hour: "21:06",
    place: "Dallas",
    clientName: "Becky Sharp",
    clientEmail: "johnny.stanley@outlook.com",
    deliveryCompany: "DHL",
    trackingCode: "967-202782",
    product:
      "Furry 80mm Sandal, Maxi Coat, Multi Dress, Body Wrap Dress, +2 more",
    price: "$6,739.25",
    paymentMethodType: "PayPal",
    paymentMethod: "",
  },
];

export const MockedPages = [
  { name: "Dashboard" },
  { name: "Orders" },
  { name: "Products" },
  { name: "Clients" },
  { name: "Stores" },
  { name: "Promo Codes" },
  { name: "Reports" },
  { name: "Support" },
];
